// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmBCnhNGfAwDDA8Ec-DbKpSUGNDB1YOpM',
    appId: '1:430070391026:web:5a6be969a5bb76900e706b',
    messagingSenderId: '430070391026',
    projectId: 'chattingus-c4b25',
    authDomain: 'chattingus-c4b25.firebaseapp.com',
    storageBucket: 'chattingus-c4b25.firebasestorage.app',
    measurementId: 'G-68SYSMS1JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0m8e9X78kCY8FW_x5i8IVdVP9SMbHviQ',
    appId: '1:430070391026:android:cc0fb46269674b940e706b',
    messagingSenderId: '430070391026',
    projectId: 'chattingus-c4b25',
    storageBucket: 'chattingus-c4b25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZpvkUsg4vHMegqLTvXiFM8SM1lXI3OuU',
    appId: '1:430070391026:ios:139b459cdf90537b0e706b',
    messagingSenderId: '430070391026',
    projectId: 'chattingus-c4b25',
    storageBucket: 'chattingus-c4b25.firebasestorage.app',
    iosBundleId: 'com.example.chattingus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZpvkUsg4vHMegqLTvXiFM8SM1lXI3OuU',
    appId: '1:430070391026:ios:139b459cdf90537b0e706b',
    messagingSenderId: '430070391026',
    projectId: 'chattingus-c4b25',
    storageBucket: 'chattingus-c4b25.firebasestorage.app',
    iosBundleId: 'com.example.chattingus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmBCnhNGfAwDDA8Ec-DbKpSUGNDB1YOpM',
    appId: '1:430070391026:web:1eeb904ac958762a0e706b',
    messagingSenderId: '430070391026',
    projectId: 'chattingus-c4b25',
    authDomain: 'chattingus-c4b25.firebaseapp.com',
    storageBucket: 'chattingus-c4b25.firebasestorage.app',
    measurementId: 'G-4D3RTDKBVH',
  );
}
